# Generated by Django 5.1.1 on 2024-10-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_profile_city_profile_country_profile_firts_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firts_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
